# Generated by Django 5.2 on 2025-05-01 02:21

from django.db import migrations
from django.db import migrations


def create_initial_statuses(apps, schemaeditor):
    """
    Create initial statuses for the Status model.
    """
    entries = {
        "Published": "Published-- A post that is publicly visible.",
        "Draft": "Draft-- A post that is only visible to the author.",
        "Archived": "Archived-- An older post, visible to the author and admins."
    }
    Status = apps.get_model('posts', 'Status')
    for key, value in entries.items():
        status_object = Status(name=key, description=value)
        status_object.save()

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_statuses), # This will create the initial statuses for the Status model. Reference the function create_initial_statuses.
    ]
